### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by adocampo** [zack-ashen/keep-cli#2]
Hi there, 
I'm also a big fan of the command line, so I'm glad to see your project alive! Thank you for the good job done so far! :D

I'm trying keep-cli, it somehow works, but it finally fails, let me put my first impressions.
After installing it via AUR, it seems to have some missing python dependencies, so I'd installed them, those were:
- gkeepapi
- pyfiglet
- keyring
- argparse

After installing all those dependencies, it starts, it ask for a username (email) and for the password, and ask to store it (I'm a bit afraid to "store" my gmail password to an unknown guy (that's you) so how about using OAuth2?)

Once fired up, it shows some cards, and then it throws an exception
![image](https://user-images.githubusercontent.com/2266612/87529320-1b5e2880-c68f-11ea-94bd-27b6b567b687.png)

```
Traceback (most recent call last):
  File "/usr/bin/keep-cli", line 33, in <module>
    sys.exit(load_entry_point('keep-cli==0.1.15', 'console_scripts', 'keep-cli')())
  File "/usr/lib/python3.8/site-packages/keep/keep.py", line 574, in main
    parse_arguments()
  File "/usr/lib/python3.8/site-packages/keep/keep.py", line 560, in parse_arguments
    note_view()
  File "/usr/lib/python3.8/site-packages/keep/keep.py", line 58, in note_view
    NoteGrid.print_grid(note_list, continuePrintingRow)
  File "/usr/lib/python3.8/site-packages/keep/NoteGrid.py", line 174, in print_grid
    print_grid(nested_list, continue_printing_row, columnEndPos + 1)
  File "/usr/lib/python3.8/site-packages/keep/NoteGrid.py", line 174, in print_grid
    print_grid(nested_list, continue_printing_row, columnEndPos + 1)
  File "/usr/lib/python3.8/site-packages/keep/NoteGrid.py", line 144, in print_grid
    max_nested_list_length = max(len(i) for i in nested_list[start_pos:columnEndPos + 1])
ValueError: max() arg is an empty sequence
```

**Comment by zack-ashen** [comment]
Hi! Thanks so much for your feedback and sorry for taking a while to respond. I've looked over your feedback and I have tried to rectify a lot of the problems you were encountering. I also have a couple of questions as far as features you may want to see.

As far as the PKGBUILD goes for the AUR, I think I just messed up writing it for a python package and I thought it should've installed the dependencies. I'm going to look into this further and should have it fixed shortly. I am using keyring to store the passwords currently which I have used in the past with other similar projects, so the password is not stored anywhere the project. 

The error message you were seeing I have addressed and will be pushing a new build today to hopefully resolve that. However, please let me know if it doesn't. Furthermore, one thing I was curious about is whether it would be better from a usability standpoint to have notes not appear in the current tiled view, but rather have one note appear at a time and use the arrow keys to scroll through your notes?

Finally, there are few more known bugs that I am currently working on getting fixed so I may take this repo down for a short period while I fix those problems and then re-launch once everything is working smoothly.

**Comment by adocampo** [comment]
Sorry for the delay, we're on different timezones :P 

> Furthermore, one thing I was curious about is whether it would be better from a usability standpoint to have notes not appear in the current tiled view, but rather have one note appear at a time and use the arrow keys to scroll through your notes?

I think the "card" view is quite original, there is another google keep CLI tool out there (gkeep) showing notes in a list, and well, is pretty inconvenient because you need to list all your notes, then grab from the output the ID or exact name, and then run the command again and pass as parameter the ID to edit or do something with that note... your approach in this more graphical way is more fun and practical. But as it exits immediately, I don't know yet how can I move between notes, enter and edit one, filter by name or tag and show just those notes which match, etc. As I have hundreds of notes, moving one by one can be frustrating, no matter if is in tiled view or one note by one.
From usability point of view, I like the "card" view, and moving among notes with cursor (or `jkhl`), enter the selected note for edit with `Intro` key, exiting with `Escape` key, and filter/search by name (insensitive) or by content with `/`
